/*
* generated by Xtext
*/
package org.xtext.tl.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cModelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cModelFunctionParserRuleCall_0_0 = (RuleCall)cModelAssignment_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Model:
		//	(model+=function LC?)*;
		public ParserRule getRule() { return rule; }

		//(model+=function LC?)*
		public Group getGroup() { return cGroup; }

		//model+=function
		public Assignment getModelAssignment_0() { return cModelAssignment_0; }

		//function
		public RuleCall getModelFunctionParserRuleCall_0_0() { return cModelFunctionParserRuleCall_0_0; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1() { return cLCTerminalRuleCall_1; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cFunNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFunNameSYMBOLESTerminalRuleCall_2_0 = (RuleCall)cFunNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cLCTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cDefAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDefDefinitonParserRuleCall_5_0 = (RuleCall)cDefAssignment_5.eContents().get(0);
		
		//function:
		//	"function" LC funName=SYMBOLES ":" LC def=Definiton;
		public ParserRule getRule() { return rule; }

		//"function" LC funName=SYMBOLES ":" LC def=Definiton
		public Group getGroup() { return cGroup; }

		//"function"
		public Keyword getFunctionKeyword_0() { return cFunctionKeyword_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_1() { return cLCTerminalRuleCall_1; }

		//funName=SYMBOLES
		public Assignment getFunNameAssignment_2() { return cFunNameAssignment_2; }

		//SYMBOLES
		public RuleCall getFunNameSYMBOLESTerminalRuleCall_2_0() { return cFunNameSYMBOLESTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//LC
		public RuleCall getLCTerminalRuleCall_4() { return cLCTerminalRuleCall_4; }

		//def=Definiton
		public Assignment getDefAssignment_5() { return cDefAssignment_5; }

		//Definiton
		public RuleCall getDefDefinitonParserRuleCall_5_0() { return cDefDefinitonParserRuleCall_5_0; }
	}

	public class DefinitonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Definiton");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cInputVarsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInputVarsInputParserRuleCall_2_0 = (RuleCall)cInputVarsAssignment_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cPercentSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCommandListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCommandListCommandsParserRuleCall_5_0 = (RuleCall)cCommandListAssignment_5.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Keyword cPercentSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cWriteKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final RuleCall cLCTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final Assignment cOutputVarsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cOutputVarsOutputParserRuleCall_10_0 = (RuleCall)cOutputVarsAssignment_10.eContents().get(0);
		
		//Definiton:
		//	"read" LC inputVars=Input LC "%" commandList=Commands LC "%" "write" LC outputVars=Output;
		public ParserRule getRule() { return rule; }

		//"read" LC inputVars=Input LC "%" commandList=Commands LC "%" "write" LC outputVars=Output
		public Group getGroup() { return cGroup; }

		//"read"
		public Keyword getReadKeyword_0() { return cReadKeyword_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_1() { return cLCTerminalRuleCall_1; }

		//inputVars=Input
		public Assignment getInputVarsAssignment_2() { return cInputVarsAssignment_2; }

		//Input
		public RuleCall getInputVarsInputParserRuleCall_2_0() { return cInputVarsInputParserRuleCall_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_3() { return cLCTerminalRuleCall_3; }

		//"%"
		public Keyword getPercentSignKeyword_4() { return cPercentSignKeyword_4; }

		//commandList=Commands
		public Assignment getCommandListAssignment_5() { return cCommandListAssignment_5; }

		//Commands
		public RuleCall getCommandListCommandsParserRuleCall_5_0() { return cCommandListCommandsParserRuleCall_5_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_6() { return cLCTerminalRuleCall_6; }

		//"%"
		public Keyword getPercentSignKeyword_7() { return cPercentSignKeyword_7; }

		//"write"
		public Keyword getWriteKeyword_8() { return cWriteKeyword_8; }

		//LC
		public RuleCall getLCTerminalRuleCall_9() { return cLCTerminalRuleCall_9; }

		//outputVars=Output
		public Assignment getOutputVarsAssignment_10() { return cOutputVarsAssignment_10; }

		//Output
		public RuleCall getOutputVarsOutputParserRuleCall_10_0() { return cOutputVarsOutputParserRuleCall_10_0; }
	}

	public class InputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Input");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVVARIABLETerminalRuleCall_0_0 = (RuleCall)cVAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cV2Assignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cV2VARIABLETerminalRuleCall_1_2_0 = (RuleCall)cV2Assignment_1_2.eContents().get(0);
		
		//Input:
		//	v=VARIABLE ("," LC? v2+=VARIABLE)*;
		public ParserRule getRule() { return rule; }

		//v=VARIABLE ("," LC? v2+=VARIABLE)*
		public Group getGroup() { return cGroup; }

		//v=VARIABLE
		public Assignment getVAssignment_0() { return cVAssignment_0; }

		//VARIABLE
		public RuleCall getVVARIABLETerminalRuleCall_0_0() { return cVVARIABLETerminalRuleCall_0_0; }

		//("," LC? v2+=VARIABLE)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1_1() { return cLCTerminalRuleCall_1_1; }

		//v2+=VARIABLE
		public Assignment getV2Assignment_1_2() { return cV2Assignment_1_2; }

		//VARIABLE
		public RuleCall getV2VARIABLETerminalRuleCall_1_2_0() { return cV2VARIABLETerminalRuleCall_1_2_0; }
	}

	public class OutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Output");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVVARIABLETerminalRuleCall_0_0 = (RuleCall)cVAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cV2Assignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cV2VARIABLETerminalRuleCall_1_2_0 = (RuleCall)cV2Assignment_1_2.eContents().get(0);
		
		//Output:
		//	v=VARIABLE ("," LC? v2+=VARIABLE)*;
		public ParserRule getRule() { return rule; }

		//v=VARIABLE ("," LC? v2+=VARIABLE)*
		public Group getGroup() { return cGroup; }

		//v=VARIABLE
		public Assignment getVAssignment_0() { return cVAssignment_0; }

		//VARIABLE
		public RuleCall getVVARIABLETerminalRuleCall_0_0() { return cVVARIABLETerminalRuleCall_0_0; }

		//("," LC? v2+=VARIABLE)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1_1() { return cLCTerminalRuleCall_1_1; }

		//v2+=VARIABLE
		public Assignment getV2Assignment_1_2() { return cV2Assignment_1_2; }

		//VARIABLE
		public RuleCall getV2VARIABLETerminalRuleCall_1_2_0() { return cV2VARIABLETerminalRuleCall_1_2_0; }
	}

	public class CommandsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Commands");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCCommandParserRuleCall_0_0 = (RuleCall)cCAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cCAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cCCommandParserRuleCall_1_2_0 = (RuleCall)cCAssignment_1_2.eContents().get(0);
		
		//Commands:
		//	c+=Command (";" LC? c+=Command)*;
		public ParserRule getRule() { return rule; }

		//c+=Command (";" LC? c+=Command)*
		public Group getGroup() { return cGroup; }

		//c+=Command
		public Assignment getCAssignment_0() { return cCAssignment_0; }

		//Command
		public RuleCall getCCommandParserRuleCall_0_0() { return cCCommandParserRuleCall_0_0; }

		//(";" LC? c+=Command)*
		public Group getGroup_1() { return cGroup_1; }

		//";"
		public Keyword getSemicolonKeyword_1_0() { return cSemicolonKeyword_1_0; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1_1() { return cLCTerminalRuleCall_1_1; }

		//c+=Command
		public Assignment getCAssignment_1_2() { return cCAssignment_1_2; }

		//Command
		public RuleCall getCCommandParserRuleCall_1_2_0() { return cCCommandParserRuleCall_1_2_0; }
	}

	public class VarsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Vars");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cVARIABLETerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cVarsParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//Vars:
		//	VARIABLE ("," Vars)?;
		public ParserRule getRule() { return rule; }

		//VARIABLE ("," Vars)?
		public Group getGroup() { return cGroup; }

		//VARIABLE
		public RuleCall getVARIABLETerminalRuleCall_0() { return cVARIABLETerminalRuleCall_0; }

		//("," Vars)?
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//Vars
		public RuleCall getVarsParserRuleCall_1_1() { return cVarsParserRuleCall_1_1; }
	}

	public class ExprsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Exprs");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cExpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cExpExprsParserRuleCall_1_1_0 = (RuleCall)cExpAssignment_1_1.eContents().get(0);
		
		//Exprs:
		//	Expr ("," exp=Exprs)?;
		public ParserRule getRule() { return rule; }

		//Expr ("," exp=Exprs)?
		public Group getGroup() { return cGroup; }

		//Expr
		public RuleCall getExprParserRuleCall_0() { return cExprParserRuleCall_0; }

		//("," exp=Exprs)?
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//exp=Exprs
		public Assignment getExpAssignment_1_1() { return cExpAssignment_1_1; }

		//Exprs
		public RuleCall getExpExprsParserRuleCall_1_1_0() { return cExpExprsParserRuleCall_1_1_0; }
	}

	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cCommandAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cNopKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cVarLAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cVarLVarsParserRuleCall_1_0_0 = (RuleCall)cVarLAssignment_1_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cColonEqualsSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cLCTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final Assignment cExpLAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cExpLExprsParserRuleCall_1_4_0 = (RuleCall)cExpLAssignment_1_4.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cNomAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Keyword cNomWhileKeyword_2_0_0 = (Keyword)cNomAssignment_2_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Assignment cExpAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cExpExprParserRuleCall_2_2_0 = (RuleCall)cExpAssignment_2_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		private final Keyword cDoKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final RuleCall cLCTerminalRuleCall_2_5 = (RuleCall)cGroup_2.eContents().get(5);
		private final Assignment cC1Assignment_2_6 = (Assignment)cGroup_2.eContents().get(6);
		private final RuleCall cC1CommandsParserRuleCall_2_6_0 = (RuleCall)cC1Assignment_2_6.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_2_7 = (RuleCall)cGroup_2.eContents().get(7);
		private final Keyword cOdKeyword_2_8 = (Keyword)cGroup_2.eContents().get(8);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cNomAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final Keyword cNomForKeyword_3_0_0 = (Keyword)cNomAssignment_3_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Assignment cExpAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cExpExprParserRuleCall_3_2_0 = (RuleCall)cExpAssignment_3_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_3_3 = (RuleCall)cGroup_3.eContents().get(3);
		private final Keyword cDoKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final RuleCall cLCTerminalRuleCall_3_5 = (RuleCall)cGroup_3.eContents().get(5);
		private final Assignment cC1Assignment_3_6 = (Assignment)cGroup_3.eContents().get(6);
		private final RuleCall cC1CommandsParserRuleCall_3_6_0 = (RuleCall)cC1Assignment_3_6.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_3_7 = (RuleCall)cGroup_3.eContents().get(7);
		private final Keyword cOdKeyword_3_8 = (Keyword)cGroup_3.eContents().get(8);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Assignment cNomAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final Keyword cNomForeachKeyword_4_0_0 = (Keyword)cNomAssignment_4_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final Assignment cExp1Assignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cExp1ExprParserRuleCall_4_2_0 = (RuleCall)cExp1Assignment_4_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_4_3 = (RuleCall)cGroup_4.eContents().get(3);
		private final Keyword cInKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final RuleCall cLCTerminalRuleCall_4_5 = (RuleCall)cGroup_4.eContents().get(5);
		private final Assignment cExp2Assignment_4_6 = (Assignment)cGroup_4.eContents().get(6);
		private final RuleCall cExp2ExprParserRuleCall_4_6_0 = (RuleCall)cExp2Assignment_4_6.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_4_7 = (RuleCall)cGroup_4.eContents().get(7);
		private final Keyword cDoKeyword_4_8 = (Keyword)cGroup_4.eContents().get(8);
		private final RuleCall cLCTerminalRuleCall_4_9 = (RuleCall)cGroup_4.eContents().get(9);
		private final Assignment cC1Assignment_4_10 = (Assignment)cGroup_4.eContents().get(10);
		private final RuleCall cC1CommandsParserRuleCall_4_10_0 = (RuleCall)cC1Assignment_4_10.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_4_11 = (RuleCall)cGroup_4.eContents().get(11);
		private final Keyword cOdKeyword_4_12 = (Keyword)cGroup_4.eContents().get(12);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Assignment cNomAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final Keyword cNomIfKeyword_5_0_0 = (Keyword)cNomAssignment_5_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_5_1 = (RuleCall)cGroup_5.eContents().get(1);
		private final Assignment cExpAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cExpExprParserRuleCall_5_2_0 = (RuleCall)cExpAssignment_5_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_5_3 = (RuleCall)cGroup_5.eContents().get(3);
		private final Keyword cThenKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final RuleCall cLCTerminalRuleCall_5_5 = (RuleCall)cGroup_5.eContents().get(5);
		private final Assignment cC1Assignment_5_6 = (Assignment)cGroup_5.eContents().get(6);
		private final RuleCall cC1CommandsParserRuleCall_5_6_0 = (RuleCall)cC1Assignment_5_6.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_5_7 = (RuleCall)cGroup_5.eContents().get(7);
		private final Group cGroup_5_8 = (Group)cGroup_5.eContents().get(8);
		private final Keyword cElseKeyword_5_8_0 = (Keyword)cGroup_5_8.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_5_8_1 = (RuleCall)cGroup_5_8.eContents().get(1);
		private final Assignment cC2Assignment_5_8_2 = (Assignment)cGroup_5_8.eContents().get(2);
		private final RuleCall cC2CommandsParserRuleCall_5_8_2_0 = (RuleCall)cC2Assignment_5_8_2.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_5_8_3 = (RuleCall)cGroup_5_8.eContents().get(3);
		private final Keyword cFiKeyword_5_9 = (Keyword)cGroup_5.eContents().get(9);
		
		//Command:
		//	{Command} "nop" | varL=Vars LC? ":=" LC? expL=Exprs | nom="while" LC exp=Expr LC "do" LC c1=Commands LC "od" |
		//	nom="for" LC exp=Expr LC "do" LC c1=Commands LC "od" | nom="foreach" LC exp1=Expr LC "in" LC exp2=Expr LC "do" LC
		//	c1=Commands LC "od" | nom="if" LC exp=Expr LC "then" LC c1=Commands LC ("else" LC c2=Commands LC)? "fi";
		public ParserRule getRule() { return rule; }

		//{Command} "nop" | varL=Vars LC? ":=" LC? expL=Exprs | nom="while" LC exp=Expr LC "do" LC c1=Commands LC "od" | nom="for"
		//LC exp=Expr LC "do" LC c1=Commands LC "od" | nom="foreach" LC exp1=Expr LC "in" LC exp2=Expr LC "do" LC c1=Commands LC
		//"od" | nom="if" LC exp=Expr LC "then" LC c1=Commands LC ("else" LC c2=Commands LC)? "fi"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{Command} "nop"
		public Group getGroup_0() { return cGroup_0; }

		//{Command}
		public Action getCommandAction_0_0() { return cCommandAction_0_0; }

		//"nop"
		public Keyword getNopKeyword_0_1() { return cNopKeyword_0_1; }

		//varL=Vars LC? ":=" LC? expL=Exprs
		public Group getGroup_1() { return cGroup_1; }

		//varL=Vars
		public Assignment getVarLAssignment_1_0() { return cVarLAssignment_1_0; }

		//Vars
		public RuleCall getVarLVarsParserRuleCall_1_0_0() { return cVarLVarsParserRuleCall_1_0_0; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1_1() { return cLCTerminalRuleCall_1_1; }

		//":="
		public Keyword getColonEqualsSignKeyword_1_2() { return cColonEqualsSignKeyword_1_2; }

		//LC?
		public RuleCall getLCTerminalRuleCall_1_3() { return cLCTerminalRuleCall_1_3; }

		//expL=Exprs
		public Assignment getExpLAssignment_1_4() { return cExpLAssignment_1_4; }

		//Exprs
		public RuleCall getExpLExprsParserRuleCall_1_4_0() { return cExpLExprsParserRuleCall_1_4_0; }

		//nom="while" LC exp=Expr LC "do" LC c1=Commands LC "od"
		public Group getGroup_2() { return cGroup_2; }

		//nom="while"
		public Assignment getNomAssignment_2_0() { return cNomAssignment_2_0; }

		//"while"
		public Keyword getNomWhileKeyword_2_0_0() { return cNomWhileKeyword_2_0_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_2_1() { return cLCTerminalRuleCall_2_1; }

		//exp=Expr
		public Assignment getExpAssignment_2_2() { return cExpAssignment_2_2; }

		//Expr
		public RuleCall getExpExprParserRuleCall_2_2_0() { return cExpExprParserRuleCall_2_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_2_3() { return cLCTerminalRuleCall_2_3; }

		//"do"
		public Keyword getDoKeyword_2_4() { return cDoKeyword_2_4; }

		//LC
		public RuleCall getLCTerminalRuleCall_2_5() { return cLCTerminalRuleCall_2_5; }

		//c1=Commands
		public Assignment getC1Assignment_2_6() { return cC1Assignment_2_6; }

		//Commands
		public RuleCall getC1CommandsParserRuleCall_2_6_0() { return cC1CommandsParserRuleCall_2_6_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_2_7() { return cLCTerminalRuleCall_2_7; }

		//"od"
		public Keyword getOdKeyword_2_8() { return cOdKeyword_2_8; }

		//nom="for" LC exp=Expr LC "do" LC c1=Commands LC "od"
		public Group getGroup_3() { return cGroup_3; }

		//nom="for"
		public Assignment getNomAssignment_3_0() { return cNomAssignment_3_0; }

		//"for"
		public Keyword getNomForKeyword_3_0_0() { return cNomForKeyword_3_0_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_3_1() { return cLCTerminalRuleCall_3_1; }

		//exp=Expr
		public Assignment getExpAssignment_3_2() { return cExpAssignment_3_2; }

		//Expr
		public RuleCall getExpExprParserRuleCall_3_2_0() { return cExpExprParserRuleCall_3_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_3_3() { return cLCTerminalRuleCall_3_3; }

		//"do"
		public Keyword getDoKeyword_3_4() { return cDoKeyword_3_4; }

		//LC
		public RuleCall getLCTerminalRuleCall_3_5() { return cLCTerminalRuleCall_3_5; }

		//c1=Commands
		public Assignment getC1Assignment_3_6() { return cC1Assignment_3_6; }

		//Commands
		public RuleCall getC1CommandsParserRuleCall_3_6_0() { return cC1CommandsParserRuleCall_3_6_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_3_7() { return cLCTerminalRuleCall_3_7; }

		//"od"
		public Keyword getOdKeyword_3_8() { return cOdKeyword_3_8; }

		//nom="foreach" LC exp1=Expr LC "in" LC exp2=Expr LC "do" LC c1=Commands LC "od"
		public Group getGroup_4() { return cGroup_4; }

		//nom="foreach"
		public Assignment getNomAssignment_4_0() { return cNomAssignment_4_0; }

		//"foreach"
		public Keyword getNomForeachKeyword_4_0_0() { return cNomForeachKeyword_4_0_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_1() { return cLCTerminalRuleCall_4_1; }

		//exp1=Expr
		public Assignment getExp1Assignment_4_2() { return cExp1Assignment_4_2; }

		//Expr
		public RuleCall getExp1ExprParserRuleCall_4_2_0() { return cExp1ExprParserRuleCall_4_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_3() { return cLCTerminalRuleCall_4_3; }

		//"in"
		public Keyword getInKeyword_4_4() { return cInKeyword_4_4; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_5() { return cLCTerminalRuleCall_4_5; }

		//exp2=Expr
		public Assignment getExp2Assignment_4_6() { return cExp2Assignment_4_6; }

		//Expr
		public RuleCall getExp2ExprParserRuleCall_4_6_0() { return cExp2ExprParserRuleCall_4_6_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_7() { return cLCTerminalRuleCall_4_7; }

		//"do"
		public Keyword getDoKeyword_4_8() { return cDoKeyword_4_8; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_9() { return cLCTerminalRuleCall_4_9; }

		//c1=Commands
		public Assignment getC1Assignment_4_10() { return cC1Assignment_4_10; }

		//Commands
		public RuleCall getC1CommandsParserRuleCall_4_10_0() { return cC1CommandsParserRuleCall_4_10_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_4_11() { return cLCTerminalRuleCall_4_11; }

		//"od"
		public Keyword getOdKeyword_4_12() { return cOdKeyword_4_12; }

		//nom="if" LC exp=Expr LC "then" LC c1=Commands LC ("else" LC c2=Commands LC)? "fi"
		public Group getGroup_5() { return cGroup_5; }

		//nom="if"
		public Assignment getNomAssignment_5_0() { return cNomAssignment_5_0; }

		//"if"
		public Keyword getNomIfKeyword_5_0_0() { return cNomIfKeyword_5_0_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_1() { return cLCTerminalRuleCall_5_1; }

		//exp=Expr
		public Assignment getExpAssignment_5_2() { return cExpAssignment_5_2; }

		//Expr
		public RuleCall getExpExprParserRuleCall_5_2_0() { return cExpExprParserRuleCall_5_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_3() { return cLCTerminalRuleCall_5_3; }

		//"then"
		public Keyword getThenKeyword_5_4() { return cThenKeyword_5_4; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_5() { return cLCTerminalRuleCall_5_5; }

		//c1=Commands
		public Assignment getC1Assignment_5_6() { return cC1Assignment_5_6; }

		//Commands
		public RuleCall getC1CommandsParserRuleCall_5_6_0() { return cC1CommandsParserRuleCall_5_6_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_7() { return cLCTerminalRuleCall_5_7; }

		//("else" LC c2=Commands LC)?
		public Group getGroup_5_8() { return cGroup_5_8; }

		//"else"
		public Keyword getElseKeyword_5_8_0() { return cElseKeyword_5_8_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_8_1() { return cLCTerminalRuleCall_5_8_1; }

		//c2=Commands
		public Assignment getC2Assignment_5_8_2() { return cC2Assignment_5_8_2; }

		//Commands
		public RuleCall getC2CommandsParserRuleCall_5_8_2_0() { return cC2CommandsParserRuleCall_5_8_2_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_5_8_3() { return cLCTerminalRuleCall_5_8_3; }

		//"fi"
		public Keyword getFiKeyword_5_9() { return cFiKeyword_5_9; }
	}

	public class ExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cExprSimpleAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cExprSimpleExprSimpleParserRuleCall_0_0 = (RuleCall)cExprSimpleAssignment_0.eContents().get(0);
		private final Assignment cExpEtAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cExpEtAndParserRuleCall_1_0 = (RuleCall)cExpEtAssignment_1.eContents().get(0);
		private final Assignment cExpTerminaleAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cExpTerminaleExprTermParserRuleCall_2_0 = (RuleCall)cExpTerminaleAssignment_2.eContents().get(0);
		
		//Expr:
		//	exprSimple=ExprSimple | expEt=And | expTerminale=ExprTerm;
		public ParserRule getRule() { return rule; }

		//exprSimple=ExprSimple | expEt=And | expTerminale=ExprTerm
		public Alternatives getAlternatives() { return cAlternatives; }

		//exprSimple=ExprSimple
		public Assignment getExprSimpleAssignment_0() { return cExprSimpleAssignment_0; }

		//ExprSimple
		public RuleCall getExprSimpleExprSimpleParserRuleCall_0_0() { return cExprSimpleExprSimpleParserRuleCall_0_0; }

		//expEt=And
		public Assignment getExpEtAssignment_1() { return cExpEtAssignment_1; }

		//And
		public RuleCall getExpEtAndParserRuleCall_1_0() { return cExpEtAndParserRuleCall_1_0; }

		//expTerminale=ExprTerm
		public Assignment getExpTerminaleAssignment_2() { return cExpTerminaleAssignment_2; }

		//ExprTerm
		public RuleCall getExpTerminaleExprTermParserRuleCall_2_0() { return cExpTerminaleExprTermParserRuleCall_2_0; }
	}

	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExpOuAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cExpOuOrParserRuleCall_0_0 = (RuleCall)cExpOuAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cAndKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Assignment cExpOu2Assignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cExpOu2OrParserRuleCall_1_3_0 = (RuleCall)cExpOu2Assignment_1_3.eContents().get(0);
		
		////Ou += Or (LC 'and' LC Or) *
		//And:
		//	expOu=Or (LC "and" LC expOu2+=Or)*;
		public ParserRule getRule() { return rule; }

		//expOu=Or (LC "and" LC expOu2+=Or)*
		public Group getGroup() { return cGroup; }

		//expOu=Or
		public Assignment getExpOuAssignment_0() { return cExpOuAssignment_0; }

		//Or
		public RuleCall getExpOuOrParserRuleCall_0_0() { return cExpOuOrParserRuleCall_0_0; }

		//(LC "and" LC expOu2+=Or)*
		public Group getGroup_1() { return cGroup_1; }

		//LC
		public RuleCall getLCTerminalRuleCall_1_0() { return cLCTerminalRuleCall_1_0; }

		//"and"
		public Keyword getAndKeyword_1_1() { return cAndKeyword_1_1; }

		//LC
		public RuleCall getLCTerminalRuleCall_1_2() { return cLCTerminalRuleCall_1_2; }

		//expOu2+=Or
		public Assignment getExpOu2Assignment_1_3() { return cExpOu2Assignment_1_3; }

		//Or
		public RuleCall getExpOu2OrParserRuleCall_1_3_0() { return cExpOu2OrParserRuleCall_1_3_0; }
	}

	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExpNonAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cExpNonNotParserRuleCall_0_0 = (RuleCall)cExpNonAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cOrKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Assignment cExpNon2Assignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cExpNon2NotParserRuleCall_1_3_0 = (RuleCall)cExpNon2Assignment_1_3.eContents().get(0);
		
		//Or:
		//	expNon=Not (LC "or" LC expNon2+=Not)*;
		public ParserRule getRule() { return rule; }

		//expNon=Not (LC "or" LC expNon2+=Not)*
		public Group getGroup() { return cGroup; }

		//expNon=Not
		public Assignment getExpNonAssignment_0() { return cExpNonAssignment_0; }

		//Not
		public RuleCall getExpNonNotParserRuleCall_0_0() { return cExpNonNotParserRuleCall_0_0; }

		//(LC "or" LC expNon2+=Not)*
		public Group getGroup_1() { return cGroup_1; }

		//LC
		public RuleCall getLCTerminalRuleCall_1_0() { return cLCTerminalRuleCall_1_0; }

		//"or"
		public Keyword getOrKeyword_1_1() { return cOrKeyword_1_1; }

		//LC
		public RuleCall getLCTerminalRuleCall_1_2() { return cLCTerminalRuleCall_1_2; }

		//expNon2+=Not
		public Assignment getExpNon2Assignment_1_3() { return cExpNon2Assignment_1_3; }

		//Not
		public RuleCall getExpNon2NotParserRuleCall_1_3_0() { return cExpNon2NotParserRuleCall_1_3_0; }
	}

	public class NotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Not");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cNonAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Keyword cNonNotKeyword_0_0_0 = (Keyword)cNonAssignment_0_0.eContents().get(0);
		private final RuleCall cLCTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Assignment cExpEqAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpEqEqParserRuleCall_1_0 = (RuleCall)cExpEqAssignment_1.eContents().get(0);
		
		//Not:
		//	(non+="not" LC)* expEq=Eq;
		public ParserRule getRule() { return rule; }

		//(non+="not" LC)* expEq=Eq
		public Group getGroup() { return cGroup; }

		//(non+="not" LC)*
		public Group getGroup_0() { return cGroup_0; }

		//non+="not"
		public Assignment getNonAssignment_0_0() { return cNonAssignment_0_0; }

		//"not"
		public Keyword getNonNotKeyword_0_0_0() { return cNonNotKeyword_0_0_0; }

		//LC
		public RuleCall getLCTerminalRuleCall_0_1() { return cLCTerminalRuleCall_0_1; }

		//expEq=Eq
		public Assignment getExpEqAssignment_1() { return cExpEqAssignment_1; }

		//Eq
		public RuleCall getExpEqEqParserRuleCall_1_0() { return cExpEqEqParserRuleCall_1_0; }
	}

	public class EqElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Eq");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cExprEq1Assignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Alternatives cExprEq1Alternatives_0_0_0 = (Alternatives)cExprEq1Assignment_0_0.eContents().get(0);
		private final RuleCall cExprEq1ExprSimpleParserRuleCall_0_0_0_0 = (RuleCall)cExprEq1Alternatives_0_0_0.eContents().get(0);
		private final RuleCall cExprEq1ExprTermParserRuleCall_0_0_0_1 = (RuleCall)cExprEq1Alternatives_0_0_0.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cEqualsSignQuestionMarkKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final RuleCall cLCTerminalRuleCall_0_3 = (RuleCall)cGroup_0.eContents().get(3);
		private final Assignment cExprEq2Assignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final Alternatives cExprEq2Alternatives_0_4_0 = (Alternatives)cExprEq2Assignment_0_4.eContents().get(0);
		private final RuleCall cExprEq2ExprSimpleParserRuleCall_0_4_0_0 = (RuleCall)cExprEq2Alternatives_0_4_0.eContents().get(0);
		private final RuleCall cExprEq2ExprTermParserRuleCall_0_4_0_1 = (RuleCall)cExprEq2Alternatives_0_4_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cExpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cExpAlternatives_1_1_0 = (Alternatives)cExpAssignment_1_1.eContents().get(0);
		private final RuleCall cExpExprTermParserRuleCall_1_1_0_0 = (RuleCall)cExpAlternatives_1_1_0.eContents().get(0);
		private final RuleCall cExpExprSimpleParserRuleCall_1_1_0_1 = (RuleCall)cExpAlternatives_1_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Eq:
		//	exprEq1=(ExprSimple | ExprTerm) LC? "=?" LC? exprEq2=(ExprSimple | ExprTerm) | "(" exp=(ExprTerm | ExprSimple) ")";
		public ParserRule getRule() { return rule; }

		//exprEq1=(ExprSimple | ExprTerm) LC? "=?" LC? exprEq2=(ExprSimple | ExprTerm) | "(" exp=(ExprTerm | ExprSimple) ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//exprEq1=(ExprSimple | ExprTerm) LC? "=?" LC? exprEq2=(ExprSimple | ExprTerm)
		public Group getGroup_0() { return cGroup_0; }

		//exprEq1=(ExprSimple | ExprTerm)
		public Assignment getExprEq1Assignment_0_0() { return cExprEq1Assignment_0_0; }

		//ExprSimple | ExprTerm
		public Alternatives getExprEq1Alternatives_0_0_0() { return cExprEq1Alternatives_0_0_0; }

		//ExprSimple
		public RuleCall getExprEq1ExprSimpleParserRuleCall_0_0_0_0() { return cExprEq1ExprSimpleParserRuleCall_0_0_0_0; }

		//ExprTerm
		public RuleCall getExprEq1ExprTermParserRuleCall_0_0_0_1() { return cExprEq1ExprTermParserRuleCall_0_0_0_1; }

		//LC?
		public RuleCall getLCTerminalRuleCall_0_1() { return cLCTerminalRuleCall_0_1; }

		//"=?"
		public Keyword getEqualsSignQuestionMarkKeyword_0_2() { return cEqualsSignQuestionMarkKeyword_0_2; }

		//LC?
		public RuleCall getLCTerminalRuleCall_0_3() { return cLCTerminalRuleCall_0_3; }

		//exprEq2=(ExprSimple | ExprTerm)
		public Assignment getExprEq2Assignment_0_4() { return cExprEq2Assignment_0_4; }

		//ExprSimple | ExprTerm
		public Alternatives getExprEq2Alternatives_0_4_0() { return cExprEq2Alternatives_0_4_0; }

		//ExprSimple
		public RuleCall getExprEq2ExprSimpleParserRuleCall_0_4_0_0() { return cExprEq2ExprSimpleParserRuleCall_0_4_0_0; }

		//ExprTerm
		public RuleCall getExprEq2ExprTermParserRuleCall_0_4_0_1() { return cExprEq2ExprTermParserRuleCall_0_4_0_1; }

		//"(" exp=(ExprTerm | ExprSimple) ")"
		public Group getGroup_1() { return cGroup_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }

		//exp=(ExprTerm | ExprSimple)
		public Assignment getExpAssignment_1_1() { return cExpAssignment_1_1; }

		//ExprTerm | ExprSimple
		public Alternatives getExpAlternatives_1_1_0() { return cExpAlternatives_1_1_0; }

		//ExprTerm
		public RuleCall getExpExprTermParserRuleCall_1_1_0_0() { return cExpExprTermParserRuleCall_1_1_0_0; }

		//ExprSimple
		public RuleCall getExpExprSimpleParserRuleCall_1_1_0_1() { return cExpExprSimpleParserRuleCall_1_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}

	public class ExprTermElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExprTerm");
		private final Assignment cExprTermAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cExprTermAlternatives_0 = (Alternatives)cExprTermAssignment.eContents().get(0);
		private final Keyword cExprTermNilKeyword_0_0 = (Keyword)cExprTermAlternatives_0.eContents().get(0);
		private final RuleCall cExprTermVARIABLETerminalRuleCall_0_1 = (RuleCall)cExprTermAlternatives_0.eContents().get(1);
		private final RuleCall cExprTermSYMBOLESTerminalRuleCall_0_2 = (RuleCall)cExprTermAlternatives_0.eContents().get(2);
		
		//ExprTerm:
		//	ExprTerm=("nil" | VARIABLE | SYMBOLES);
		public ParserRule getRule() { return rule; }

		//ExprTerm=("nil" | VARIABLE | SYMBOLES)
		public Assignment getExprTermAssignment() { return cExprTermAssignment; }

		//"nil" | VARIABLE | SYMBOLES
		public Alternatives getExprTermAlternatives_0() { return cExprTermAlternatives_0; }

		//"nil"
		public Keyword getExprTermNilKeyword_0_0() { return cExprTermNilKeyword_0_0; }

		//VARIABLE
		public RuleCall getExprTermVARIABLETerminalRuleCall_0_1() { return cExprTermVARIABLETerminalRuleCall_0_1; }

		//SYMBOLES
		public RuleCall getExprTermSYMBOLESTerminalRuleCall_0_2() { return cExprTermSYMBOLESTerminalRuleCall_0_2; }
	}

	public class ExprSimpleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExprSimple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Assignment cMotAssignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final Alternatives cMotAlternatives_1_0_0_0 = (Alternatives)cMotAssignment_1_0_0.eContents().get(0);
		private final Keyword cMotConsKeyword_1_0_0_0_0 = (Keyword)cMotAlternatives_1_0_0_0.eContents().get(0);
		private final Keyword cMotListKeyword_1_0_0_0_1 = (Keyword)cMotAlternatives_1_0_0_0.eContents().get(1);
		private final Assignment cLexprAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cLexprLexprParserRuleCall_1_0_1_0 = (RuleCall)cLexprAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cMotAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final Alternatives cMotAlternatives_1_1_0_0 = (Alternatives)cMotAssignment_1_1_0.eContents().get(0);
		private final Keyword cMotHdKeyword_1_1_0_0_0 = (Keyword)cMotAlternatives_1_1_0_0.eContents().get(0);
		private final Keyword cMotTlKeyword_1_1_0_0_1 = (Keyword)cMotAlternatives_1_1_0_0.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		private final Assignment cExprAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cExprExprParserRuleCall_1_1_2_0 = (RuleCall)cExprAssignment_1_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExprSimple:
		//	"(" (mot=("cons" | "list") lexpr=Lexpr | mot=("hd" | "tl") LC expr=Expr) ")";
		public ParserRule getRule() { return rule; }

		//"(" (mot=("cons" | "list") lexpr=Lexpr | mot=("hd" | "tl") LC expr=Expr) ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//mot=("cons" | "list") lexpr=Lexpr | mot=("hd" | "tl") LC expr=Expr
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//mot=("cons" | "list") lexpr=Lexpr
		public Group getGroup_1_0() { return cGroup_1_0; }

		//mot=("cons" | "list")
		public Assignment getMotAssignment_1_0_0() { return cMotAssignment_1_0_0; }

		//"cons" | "list"
		public Alternatives getMotAlternatives_1_0_0_0() { return cMotAlternatives_1_0_0_0; }

		//"cons"
		public Keyword getMotConsKeyword_1_0_0_0_0() { return cMotConsKeyword_1_0_0_0_0; }

		//"list"
		public Keyword getMotListKeyword_1_0_0_0_1() { return cMotListKeyword_1_0_0_0_1; }

		//lexpr=Lexpr
		public Assignment getLexprAssignment_1_0_1() { return cLexprAssignment_1_0_1; }

		//Lexpr
		public RuleCall getLexprLexprParserRuleCall_1_0_1_0() { return cLexprLexprParserRuleCall_1_0_1_0; }

		//mot=("hd" | "tl") LC expr=Expr
		public Group getGroup_1_1() { return cGroup_1_1; }

		//mot=("hd" | "tl")
		public Assignment getMotAssignment_1_1_0() { return cMotAssignment_1_1_0; }

		//"hd" | "tl"
		public Alternatives getMotAlternatives_1_1_0_0() { return cMotAlternatives_1_1_0_0; }

		//"hd"
		public Keyword getMotHdKeyword_1_1_0_0_0() { return cMotHdKeyword_1_1_0_0_0; }

		//"tl"
		public Keyword getMotTlKeyword_1_1_0_0_1() { return cMotTlKeyword_1_1_0_0_1; }

		//LC
		public RuleCall getLCTerminalRuleCall_1_1_1() { return cLCTerminalRuleCall_1_1_1; }

		//expr=Expr
		public Assignment getExprAssignment_1_1_2() { return cExprAssignment_1_1_2; }

		//Expr
		public RuleCall getExprExprParserRuleCall_1_1_2_0() { return cExprExprParserRuleCall_1_1_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}

	public class LexprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Lexpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLCTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cExpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpExprParserRuleCall_1_0 = (RuleCall)cExpAssignment_1.eContents().get(0);
		
		//Lexpr:
		//	(LC exp+=Expr)+;
		public ParserRule getRule() { return rule; }

		//(LC exp+=Expr)+
		public Group getGroup() { return cGroup; }

		//LC
		public RuleCall getLCTerminalRuleCall_0() { return cLCTerminalRuleCall_0; }

		//exp+=Expr
		public Assignment getExpAssignment_1() { return cExpAssignment_1; }

		//Expr
		public RuleCall getExpExprParserRuleCall_1_0() { return cExpExprParserRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private FunctionElements pFunction;
	private DefinitonElements pDefiniton;
	private InputElements pInput;
	private OutputElements pOutput;
	private CommandsElements pCommands;
	private VarsElements pVars;
	private ExprsElements pExprs;
	private CommandElements pCommand;
	private ExprElements pExpr;
	private AndElements pAnd;
	private OrElements pOr;
	private NotElements pNot;
	private EqElements pEq;
	private ExprTermElements pExprTerm;
	private ExprSimpleElements pExprSimple;
	private LexprElements pLexpr;
	private TerminalRule tVARIABLE;
	private TerminalRule tSYMBOLES;
	private TerminalRule tLC;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.tl.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	(model+=function LC?)*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//function:
	//	"function" LC funName=SYMBOLES ":" LC def=Definiton;
	public FunctionElements getFunctionAccess() {
		return (pFunction != null) ? pFunction : (pFunction = new FunctionElements());
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//Definiton:
	//	"read" LC inputVars=Input LC "%" commandList=Commands LC "%" "write" LC outputVars=Output;
	public DefinitonElements getDefinitonAccess() {
		return (pDefiniton != null) ? pDefiniton : (pDefiniton = new DefinitonElements());
	}
	
	public ParserRule getDefinitonRule() {
		return getDefinitonAccess().getRule();
	}

	//Input:
	//	v=VARIABLE ("," LC? v2+=VARIABLE)*;
	public InputElements getInputAccess() {
		return (pInput != null) ? pInput : (pInput = new InputElements());
	}
	
	public ParserRule getInputRule() {
		return getInputAccess().getRule();
	}

	//Output:
	//	v=VARIABLE ("," LC? v2+=VARIABLE)*;
	public OutputElements getOutputAccess() {
		return (pOutput != null) ? pOutput : (pOutput = new OutputElements());
	}
	
	public ParserRule getOutputRule() {
		return getOutputAccess().getRule();
	}

	//Commands:
	//	c+=Command (";" LC? c+=Command)*;
	public CommandsElements getCommandsAccess() {
		return (pCommands != null) ? pCommands : (pCommands = new CommandsElements());
	}
	
	public ParserRule getCommandsRule() {
		return getCommandsAccess().getRule();
	}

	//Vars:
	//	VARIABLE ("," Vars)?;
	public VarsElements getVarsAccess() {
		return (pVars != null) ? pVars : (pVars = new VarsElements());
	}
	
	public ParserRule getVarsRule() {
		return getVarsAccess().getRule();
	}

	//Exprs:
	//	Expr ("," exp=Exprs)?;
	public ExprsElements getExprsAccess() {
		return (pExprs != null) ? pExprs : (pExprs = new ExprsElements());
	}
	
	public ParserRule getExprsRule() {
		return getExprsAccess().getRule();
	}

	//Command:
	//	{Command} "nop" | varL=Vars LC? ":=" LC? expL=Exprs | nom="while" LC exp=Expr LC "do" LC c1=Commands LC "od" |
	//	nom="for" LC exp=Expr LC "do" LC c1=Commands LC "od" | nom="foreach" LC exp1=Expr LC "in" LC exp2=Expr LC "do" LC
	//	c1=Commands LC "od" | nom="if" LC exp=Expr LC "then" LC c1=Commands LC ("else" LC c2=Commands LC)? "fi";
	public CommandElements getCommandAccess() {
		return (pCommand != null) ? pCommand : (pCommand = new CommandElements());
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}

	//Expr:
	//	exprSimple=ExprSimple | expEt=And | expTerminale=ExprTerm;
	public ExprElements getExprAccess() {
		return (pExpr != null) ? pExpr : (pExpr = new ExprElements());
	}
	
	public ParserRule getExprRule() {
		return getExprAccess().getRule();
	}

	////Ou += Or (LC 'and' LC Or) *
	//And:
	//	expOu=Or (LC "and" LC expOu2+=Or)*;
	public AndElements getAndAccess() {
		return (pAnd != null) ? pAnd : (pAnd = new AndElements());
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}

	//Or:
	//	expNon=Not (LC "or" LC expNon2+=Not)*;
	public OrElements getOrAccess() {
		return (pOr != null) ? pOr : (pOr = new OrElements());
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}

	//Not:
	//	(non+="not" LC)* expEq=Eq;
	public NotElements getNotAccess() {
		return (pNot != null) ? pNot : (pNot = new NotElements());
	}
	
	public ParserRule getNotRule() {
		return getNotAccess().getRule();
	}

	//Eq:
	//	exprEq1=(ExprSimple | ExprTerm) LC? "=?" LC? exprEq2=(ExprSimple | ExprTerm) | "(" exp=(ExprTerm | ExprSimple) ")";
	public EqElements getEqAccess() {
		return (pEq != null) ? pEq : (pEq = new EqElements());
	}
	
	public ParserRule getEqRule() {
		return getEqAccess().getRule();
	}

	//ExprTerm:
	//	ExprTerm=("nil" | VARIABLE | SYMBOLES);
	public ExprTermElements getExprTermAccess() {
		return (pExprTerm != null) ? pExprTerm : (pExprTerm = new ExprTermElements());
	}
	
	public ParserRule getExprTermRule() {
		return getExprTermAccess().getRule();
	}

	//ExprSimple:
	//	"(" (mot=("cons" | "list") lexpr=Lexpr | mot=("hd" | "tl") LC expr=Expr) ")";
	public ExprSimpleElements getExprSimpleAccess() {
		return (pExprSimple != null) ? pExprSimple : (pExprSimple = new ExprSimpleElements());
	}
	
	public ParserRule getExprSimpleRule() {
		return getExprSimpleAccess().getRule();
	}

	//Lexpr:
	//	(LC exp+=Expr)+;
	public LexprElements getLexprAccess() {
		return (pLexpr != null) ? pLexpr : (pLexpr = new LexprElements());
	}
	
	public ParserRule getLexprRule() {
		return getLexprAccess().getRule();
	}

	//terminal VARIABLE:
	//	"A".."Z" ("a".."z" | "0".."9" | "A".."Z")*;
	public TerminalRule getVARIABLERule() {
		return (tVARIABLE != null) ? tVARIABLE : (tVARIABLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "VARIABLE"));
	} 

	//terminal SYMBOLES:
	//	"a".."z" ("a".."z" | "0".."9" | "A".."Z")*;
	public TerminalRule getSYMBOLESRule() {
		return (tSYMBOLES != null) ? tSYMBOLES : (tSYMBOLES = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SYMBOLES"));
	} 

	//terminal LC:
	//	(" " | "\n" | "\t")+;
	public TerminalRule getLCRule() {
		return (tLC != null) ? tLC : (tLC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LC"));
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
