/*
* generated by Xtext
*/
package org.xtext.tl.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.tl.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.tl.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.tl.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.tl.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
					put(grammarAccess.getExprAccess().getAlternatives(), "rule__Expr__Alternatives");
					put(grammarAccess.getEqAccess().getAlternatives(), "rule__Eq__Alternatives");
					put(grammarAccess.getEqAccess().getAlternatives_0_0(), "rule__Eq__Alternatives_0_0");
					put(grammarAccess.getEqAccess().getAlternatives_0_4(), "rule__Eq__Alternatives_0_4");
					put(grammarAccess.getEqAccess().getAlternatives_1_1(), "rule__Eq__Alternatives_1_1");
					put(grammarAccess.getExprTermAccess().getAlternatives(), "rule__ExprTerm__Alternatives");
					put(grammarAccess.getExprSimpleAccess().getAlternatives_1(), "rule__ExprSimple__Alternatives_1");
					put(grammarAccess.getExprSimpleAccess().getAlternatives_1_0_0(), "rule__ExprSimple__Alternatives_1_0_0");
					put(grammarAccess.getExprSimpleAccess().getAlternatives_1_1_0(), "rule__ExprSimple__Alternatives_1_1_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getDefinitonAccess().getGroup(), "rule__Definiton__Group__0");
					put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
					put(grammarAccess.getInputAccess().getGroup_1(), "rule__Input__Group_1__0");
					put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
					put(grammarAccess.getOutputAccess().getGroup_1(), "rule__Output__Group_1__0");
					put(grammarAccess.getCommandsAccess().getGroup(), "rule__Commands__Group__0");
					put(grammarAccess.getCommandsAccess().getGroup_1(), "rule__Commands__Group_1__0");
					put(grammarAccess.getVarsAccess().getGroup(), "rule__Vars__Group__0");
					put(grammarAccess.getVarsAccess().getGroup_1(), "rule__Vars__Group_1__0");
					put(grammarAccess.getExprsAccess().getGroup(), "rule__Exprs__Group__0");
					put(grammarAccess.getExprsAccess().getGroup_1(), "rule__Exprs__Group_1__0");
					put(grammarAccess.getCommandAccess().getGroup_1(), "rule__Command__Group_1__0");
					put(grammarAccess.getCommandAccess().getGroup_2(), "rule__Command__Group_2__0");
					put(grammarAccess.getCommandAccess().getGroup_3(), "rule__Command__Group_3__0");
					put(grammarAccess.getCommandAccess().getGroup_4(), "rule__Command__Group_4__0");
					put(grammarAccess.getCommandAccess().getGroup_5(), "rule__Command__Group_5__0");
					put(grammarAccess.getCommandAccess().getGroup_5_8(), "rule__Command__Group_5_8__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
					put(grammarAccess.getNotAccess().getGroup(), "rule__Not__Group__0");
					put(grammarAccess.getNotAccess().getGroup_0(), "rule__Not__Group_0__0");
					put(grammarAccess.getEqAccess().getGroup_0(), "rule__Eq__Group_0__0");
					put(grammarAccess.getEqAccess().getGroup_1(), "rule__Eq__Group_1__0");
					put(grammarAccess.getExprSimpleAccess().getGroup(), "rule__ExprSimple__Group__0");
					put(grammarAccess.getExprSimpleAccess().getGroup_1_0(), "rule__ExprSimple__Group_1_0__0");
					put(grammarAccess.getExprSimpleAccess().getGroup_1_1(), "rule__ExprSimple__Group_1_1__0");
					put(grammarAccess.getLexprAccess().getGroup(), "rule__Lexpr__Group__0");
					put(grammarAccess.getModelAccess().getModelAssignment_0(), "rule__Model__ModelAssignment_0");
					put(grammarAccess.getFunctionAccess().getFunNameAssignment_2(), "rule__Function__FunNameAssignment_2");
					put(grammarAccess.getFunctionAccess().getDefAssignment_5(), "rule__Function__DefAssignment_5");
					put(grammarAccess.getDefinitonAccess().getInputVarsAssignment_2(), "rule__Definiton__InputVarsAssignment_2");
					put(grammarAccess.getDefinitonAccess().getCommandListAssignment_5(), "rule__Definiton__CommandListAssignment_5");
					put(grammarAccess.getDefinitonAccess().getOutputVarsAssignment_10(), "rule__Definiton__OutputVarsAssignment_10");
					put(grammarAccess.getCommandsAccess().getCAssignment_0(), "rule__Commands__CAssignment_0");
					put(grammarAccess.getCommandsAccess().getCAssignment_1_2(), "rule__Commands__CAssignment_1_2");
					put(grammarAccess.getCommandAccess().getCAssignment_5_6(), "rule__Command__CAssignment_5_6");
					put(grammarAccess.getCommandAccess().getC2Assignment_5_8_2(), "rule__Command__C2Assignment_5_8_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.tl.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.tl.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
